print(r"     /~\ ")
print(r"    ( oo|")
print(r"    _\=/_")
print(r"   /  _  \ ")
print(r"  //|/.\|\\ ")
print(r" ||  \ /  ||")
print("============")
print("|          |")
print("|          |")
print("|          |")
